### ISSUE TITLE
Inline media playback not working. (?)

### ISSUE THREAD

**Issue by norbimona** [dpa99c/cordova-plugin-inappbrowser-wkwebview#4]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
After adding `<preference name="AllowInlineMediaPlayback" value="true" /> ` to config.xml and also having both 'webkit-playsinline' & 'playsinline' tags in my html,
the videos are still being opened in fullscreen, without playing inline.

**Expected behavior:**
Videos should play in the inappbrowser instead of opening in fullscreen.

**Steps to reproduce:**
Create a new ionic project, add `<preference name="AllowInlineMediaPlayback" value="true" /> ` to your config.xml, import this plugin along with wkwebview-engine, open a website (preferably your own, or one with the 'webkit-playsinline' & 'playsinline' tags already added to videos) with any html5 video in inappbrowser, then play the video.

Note: Tested on iPhone 5s (iOS 10.3), iPhone SE (iOS 11.3), iPhone 6 (iOS 11.4.1), iPhone 7 (iOS 12 dev). None of them played videos inline. This issue appeared after switching from UIWebView to WKWebView with this plugin; before that, the videos were playing inline as expected.

Any suggestions?
Thank you in advance. 😄

**Comment by dpa99c** [comment]
There were a couple of options which are present in the original UIWebView implementation and are also supported by the [WKWebView preferences](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration?language=objc) which hadn't been migrated and this included `AllowInlineMediaPlayback`. This should now work due to the above commit.

**Comment by norbimona** [comment]
Awesome, it works now. Thank you! :)
