### ISSUE TITLE
Question original IAB <> wkwebview

### ISSUE THREAD

**Issue by Webrow** [dpa99c/cordova-plugin-inappbrowser-wkwebview#5]
Hey, 
Currently we are working on an project where the login is stored in a cookie. 
These cookies started a hell for us, where we swapped around with cookieemperror etc to get the cookies available in the IAB so the person wouldnt need to keep loggin in to the main website ( we have a website where we are making small parts native, and small parts still redirect to the website of that part). 

Are there any downfalls to using this plugin, as it seems it uses the cookie from vordova for authing the URL in the wkwebview. Is there a special reason why the original IAB hasnt been updated. Just curious and questions cause this seems to be a solution for us. 

Greetings, 

Webrow

**Comment by dpa99c** [comment]
> Are there any downfalls to using this plugin

The iOS implementation using WKWebView hasn't been exhaustively tested so there may be features of the original IAB that don't yet work.

> it seems it uses the cookie from vordova for authing the URL in the wkwebview.

Yes, it uses the shared cookie pool feature of WKWebView to shared cookies between the main Cordova Webview and IAB Webviews.

> Is there a special reason why the original IAB hasnt been updated

I have submitted [a Pull Request](https://github.com/apache/cordova-plugin-inappbrowser/pull/271) to add WKWebView to the original IAB but it has yet to be reviewed or accepted.

**Comment by Webrow** [comment]
Thank you @dpa99c I love your work !
