### ISSUE TITLE
Youtube, Vimeo, others - second played video crashes the app when opened in native player - IOS

### ISSUE THREAD

**Issue by paulincai** [dpa99c/cordova-plugin-inappbrowser-wkwebview#7]
cordova-lib: 7.1.0
cordova-ios: 4.5.4
cordova-plugin-inappbrowser: 3.0.0
Same behavior in cordova-plugin-inappbrowser

Tested with IPhone 6 - IOS latest Beta of 12, Xcode10 and Simulator for Iphone 6, IOS11.4, Simulator for Iphone XS IOS 12.

Open a Youtube link in inappbrowser. The native video player starts, all OK. Stop, tap on another suggested video. In real device app closes down. In Simulator app freezes.

The highlight in red is displayed right after tap to watch the second video.

Meaning of EXC_BAD_ACCESS

Later Edit: after more testing, I guess it happens with any video source and it seems to be an issue between the inapbrowser and the native video player

![screen shot 2018-09-14 at 12 09 54](https://user-images.githubusercontent.com/26188915/45545611-de734180-b82b-11e8-8e2f-99076ff1fcb5.png)

**Comment by dpa99c** [comment]
Closing as the WKWebView component of this plugin has now been merged into [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) via [this PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/271) so issues should now be raised against `cordova-plugin-inappbrowser`.
