### ISSUE TITLE
Toolbar color and Close button color settings disregarded

### ISSUE THREAD

**Issue by paulincai** [dpa99c/cordova-plugin-inappbrowser-wkwebview#8]
cordova-lib: 7.1.0
cordova-ios: 4.5.4
cordova-plugin-inappbrowser-wkwebview: latest commit.

Tested with IPhone 6 - IOS latest Beta of 12.
Install cordova-plugin-inappbrowser: 3.0.0, set desired color, all ok.
Uninstall cordova-plugin-inappbrowser and install cordova-plugin-inappbrowser-wkwebview. Only get default colors, settings disregarded.

**Comment by dpa99c** [comment]
Closing as the WKWebView component of this plugin has now been merged into [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) via [this PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/271) so issues should now be raised against `cordova-plugin-inappbrowser`.
