### ISSUE TITLE
Navigating to other application due to universal/app links

### ISSUE THREAD

**Issue by shridurge** [dpa99c/cordova-plugin-inappbrowser-wkwebview#9]
Thanks so much for this plugin

I have one feature request and any solution on this would be really appreciated

# Feature request

When I open my login url into inappbrowser, after login it redirected to other application due to universal/app link present as redirection url.
I want to prevent the inappbrowser to redirect to other application so that I can control the login flow and navigate back to my application. 

Any suggestions?
Thank you in advance.

**Comment by dpa99c** [comment]
The WKWebView component of this plugin has now been merged into [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) via [this PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/271) therefore you should raise any feature requests or bugs against `cordova-plugin-inappbrowser`
